### ISSUE TITLE
[Automation] Create PR to update sec-scanners-config.yaml

### ISSUE THREAD

**Issue by barchw** [kyma-project/api-gateway#1150]
**Description**

Create a scheduled, weekly job, that will update the image version in `sec-scanners-config.yaml`. PR should be added to team's GH Project to sprint and to review column.

Some script already exists, but does not create a PR: 
- https://github.com/kyma-project/istio/blob/main/.github/workflows/update-sec-scanner.yaml

**Reasons**

- Automation of manual task

Contact(s): PO; ...

Pre-reqs:
- [x] https://github.com/kyma-project/api-gateway/issues/1234

**ToDos [Developer]**
- [x] Check with kyma-security if we actually can create an automated PR (we can use some goat bot like @kyma-gopher-bot)
- [x] Use Github service account creator tool to create this account
- [x] Update Slack notification in #goat-int 

**PRs**
- [x] https://github.com/kyma-project/api-gateway/pull/1504

**ACs [PO]**
- [x] PR to update sec scan config is created once a week
- [x] PR is added to a sprint and review column 

**Attachments**
- https://github.com/kyma-project/api-gateway/issues/1234

**Follow-up Issues**
- [...]()
