### ISSUE TITLE
[API-Gateway] Drop usage of prow build jobs

### ISSUE THREAD

**Issue by videlov** [kyma-project/api-gateway#1271]
**Description**

We need to drop prow build jobs in API-Gateway Github actions. Docs:
https://github.com/kyma-project/test-infra/blob/main/cmd/image-builder/README.md#quickstart-guide

See previous tasks done for PR builds (in Notes).

**Motivation**

Neighbours want to drop prow in favour of azure dev ops jobs.

Contact(s): @Sawthis 

**ToDo [Developer]**
- [x] Fix scheduled api-gateway integration tests
- [x] Introduce image-builder in release workflows
- [x] Create test release 0.0 and clean it up afterwards
- [x] Cherry pick workflow to release 2.6
- [x] Purge test infra
- [x] Update CI/CD docs

**PRs**
- https://github.com/kyma-project/api-gateway/pull/1319
- https://github.com/kyma-project/api-gateway/pull/1323
- https://github.com/kyma-project/api-gateway/pull/1321
- https://github.com/kyma-project/api-gateway/pull/1324
- https://github.com/kyma-project/api-gateway/pull/1331
- https://github.com/kyma-project/test-infra/pull/12016
- https://github.com/kyma-project/api-gateway/pull/1333

**AC [Reviewer | PO]**
- [x] API Gateway images on main and release branch are built by neighbours provided GH Action
- [x] Fix main workflow on schedule

**DoD [Developer & Reviewer]**
- [x] Provide documentation.

**Attachments**
- [Remove Release jobs from Prow](https://github.com/kyma-project/test-infra/issues/11711)
- [Release PR workflow run](https://github.com/kyma-project/api-gateway/actions/runs/11102743980?pr=1325)
- [Create release workflow run](https://github.com/kyma-project/api-gateway/actions/runs/11103223601)
- [Release 2.6 PR workflow run](https://github.com/kyma-project/api-gateway/pull/1332)
- [Scheduled main integration run](https://github.com/kyma-project/api-gateway/actions/runs/11118931932)

**Comment by strekm** [comment]
revert main workflow cause scheduled int tests are failing
