### ISSUE TITLE
[MVP] API Gateway component

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#130]
**Description**

First version of api-gateway component responsible for installation / upgrades / deletion of api-gateway controller.

TODO:
- [x] implementation
- [x] pipelines
- [x] tests implementations
- [x] documentation
- [x] rollout

TASKS:
- [x] [APIGateway v1alpha1 proposal](https://github.com/kyma-project/api-gateway/issues/473)
- [x] [support for installation](https://github.com/kyma-project/api-gateway/issues/474)
- [x] [support for default gateway](https://github.com/kyma-project/api-gateway/issues/532)
- [x] [global.domainName dropped](https://github.com/kyma-project/api-gateway/issues/524)
- [x] [dependency test](https://github.com/kyma-project/api-gateway/issues/533)
- [x] [oathkeeper support](https://github.com/kyma-project/api-gateway/issues/560)
- [x] [support for uninstallation](https://github.com/kyma-project/api-gateway/issues/559)
- [x] [compatibility test](https://github.com/kyma-project/api-gateway/issues/562)
- [x] [discovering dependencies (gardener, istio)](https://github.com/kyma-project/api-gateway/issues/596)
- [x] security scan conf
- [x] migration POC
- [x] [UI for APIGateway CR](https://github.com/kyma-project/api-gateway/issues/563)
- [x] [2.0 release](https://github.com/kyma-project/api-gateway/releases/tag/2.0.0)
- [x] dev env migration
- [x] stage migration
- [x] prod env migration
- [x] [documentation](https://github.com/kyma-project/api-gateway/issues/436)

**Reasons**
part of modularisation

**DoD:**
- [x] provide documentation
- [ ] publish release notes and _What's New_ updates for Kyma customers
- [x] provide unit tests
- [x] test on SKR
- [x] verify [Get started guides](https://kyma-project.io/docs/kyma/latest/02-get-started/) 
- [x] verify resource limits
~~- [ ] followup issue~~
~~- [ ] create release and bump in kyma~~

**Attachments**
Based on api proposal, technical design and migration proposal (TBD)
