### ISSUE TITLE
Automated integration test for noAuth and jwt migration

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1301]
**Description**

API Gateway module offers zero downtime migration from APIRule v1beta1 to v2alpha1. This is critical functionality helping APIRule users migrate their workloads to newer version of APIRule without experiencing any disruption. Workloads should be available also during migration. 

Implement automated test checking if following scenarios:
- migration of noop APIRule to noAuth
- migration of allow APIRule to noAuth
- migration of no_auth APIRule to noAuth
- migration of Oathkeeper-based jwt APIRule to jwt

If workload under the test will respond with anything else than 200 test should fail.

Implement a shell script that would set up a cluster with Istio and API Gateway installed, that is wrapping migration integration scenarios and running in the background "downtime detector".

This test should be invoked with make test target. This test should executed on main and release branches. Additionally should run on schedule on main branch.

**PR:**
- https://github.com/kyma-project/api-gateway/pull/1312
- https://github.com/kyma-project/api-gateway/pull/1317

**TODO:**
- [x] Write script that executes a test and sends requests against the workload of an integration test
- [x] Add make target to execute the script
- [x] Extend script to run multiple scenarios sequentially
- [x] Extend script to support requests using a JWT token
- [x] Increase stability of the tests
- [x] Add GitHub Action Job that runs on merge to main
- [x] Add GitHub Action Job that runs on schedule on main
- [x] Add GitHub Action Job that runs on PR to release branches
- [x] Update CI/CD documentation
- [x] After review remove migration test from PR workflow
- [x] Update CI/CD doc links after PR merge

ACs:
- [x] green test checking migration scenarios
- [x] running on main, release and on schedule
  - -> it was sahred in daily on 24.09. that with the current structure of GHA workflows it's better to run it on PR to release branch for now.
- [x] docu updated

**Reasons**

**DoD:**
- [x] Provide documentation.
- [x] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.

**Attachments**
