### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1365]
**Description**

Istio module should support rate limiting. New CRD should be introduced to support rate limiting configuration. User should be able to limit access to given workload based on caller ID, custom header or client certificate. Introduced CRD should hide complexity of EnvoyFilters. 

TODO:
- [x] [POC local/global rate limiting](https://github.com/kyma-project/istio/issues/774)
- [x] [POC memcached/redis rate limit service](https://github.com/kyma-project/istio/issues/826)
- [x] API design
- [x] technical design
- [x] threat modeling
- [ ] [[Threat Modeling] Documentation of the potential impact of rate limiting](https://github.com/kyma-project/istio/issues/1003)
- [ ] [[Threat Modeling] End-to-end testing of Envoy filter creation](https://github.com/kyma-project/istio/issues/1002)
- [ ] implementation
- [ ] rollout

**Reasons**

**Attachments**
https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/
https://github.com/kyma-project/kyma/issues/17572
https://killercoda.com/interactive-kyma/scenario/rate-limit
