### ISSUE TITLE
RateLimit CRD

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1467]
**Description**

Introduce RateLimit CRD as described in accepted [ADR](https://github.com/kyma-project/istio/blob/main/docs/contributor/adr/0008-rate-limit.md). Implement in code and CRD validation. Creation of corresponding EnvoyFilter is out of scope of this task. New CRD should be hidden behind rate limiting [feature toggle](https://github.com/kyma-project/api-gateway/issues/1396) and should not be user facing. 

**Reasons**

**Contact**

**ToDos [Developer]**

- [x] generate CRD
- [x] implement reconcile function
- [x] implement CRD validation
- [x] implement in code validation if needed
- [x] update technical design of the module

**PRs**

- https://github.com/kyma-project/istio/pull/1157
- https://github.com/kyma-project/api-gateway/pull/1487
- https://github.com/kyma-project/api-gateway/pull/1508

**ACs [PO]**

- [x] RateLimit CRD introduced with validation
- [x] EnvoyFilter CR is not created
- [x] the CRD is hidden behind FT

**DoD [Developer & Reviewer]**

- [x] Provide unit and integration tests.
- [x] Provide documentation.
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [x] If you changed the resource limits, explain why it was needed.
- [x] If the default configuration of Istio Operator has been changed, you performed a manual upgrade test to verify that the change can be rolled out correctly.
- [x] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
~~- [ ] Add release notes.~~

**Attachments**
part of: https://github.com/kyma-project/api-gateway/issues/1365

**Follow-Up Issues**

- [...]()
