### ISSUE TITLE
Test api-gateway-manager.yaml during release process

### ISSUE THREAD

**Issue by triffer** [kyma-project/api-gateway#1472]
**Description**
The manifest release artefact ([api-gateway-manager.yaml](https://github.com/kyma-project/api-gateway/releases/download/2.9.0/api-gateway-manager.yaml) created by `make generate-manifest`) is never tested in the release process. The release process should be extended to use this manifest to deploy the manager.

**Reasons**
Make sure that all release artefacts are tested.

**ToDos [Developer]**

- [ ] ...

**PRs**

- [ ] [...]()

**ACs [PO]**

- [ ] `api-gateway-manager.yaml` is tested as part of the release process

**DoD [Developer & Reviewer]**

- [ ] Provide unit and integration tests.
- [ ] Provide documentation.
- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [ ] If you changed the resource limits, explain why it was needed.
- [ ] If the default configuration of Istio Operator has been changed, you performed a manual upgrade test to verify that the change can be rolled out correctly.
- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [ ] Add release notes.
