### ISSUE TITLE
Create release GH Workflow

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1510]
**Description**

Create / adjust release workflow that builds production image with image-builder, execute lint and unit tests, integration tests, custom domain test, upgrade tests and APIRule migration tests on k3d, AWS, GCP.

**ToDos [Developer]**

- [x] do not run tests on sec config changes and eventually version changes
- [x]  extend create release workflow to execute tests on release artefact
- [x]  failing tests should block GH Release creation
- [x]  there should be possibility to run tests if failed previously
- [x]  extend Release module template with TODO to link green create release workflow
- [x]  Add notification about release done to create release workflow at the end

**PRs**

- [x] https://github.com/kyma-project/api-gateway/pull/1493

**Attachments**

- part of: #1509
