### ISSUE TITLE
Adjust naming convention for GH Workflows Create Release

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1513]
**Description**

As described in documented [test strategy](https://github.com/kyma-project/api-gateway/issues/1511) adjust naming for GH Workflow Create Release. 

**ToDos [Developer]**

- [x] Rename files according to accepted naming convention

**PRs**

- [x] https://github.com/kyma-project/api-gateway/pull/1522
- [x] https://github.com/kyma-project/api-gateway/pull/1531

**ACs [PO]**

- [x] Workflow names and file names adapted for release related workflows
- [x] changes updated in ci-cd.md

**DoD [Developer & Reviewer]**

- [x] Provide documentation.

**Attachments**

- part of: https://github.com/kyma-project/api-gateway/issues/1509
