### ISSUE TITLE
Adjust post GH Workflow

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1515]
**Description**

implement GH workflow that should be triggered by merge to main branch. Image should be built using neighbours provided image-builder. Run lint and unit tests, integration tests, custom domain tests, upgrade test and APIRule migration tests. In the last step of the workflow which in case of a failure is a Slack notification, include information about the owner of the commit.

**ToDos [Developer]**

- [x]  lint and unit tests are run
- [x]  image built using image-builder
- [x]  integration tests are run on k3d and AWS
- [x]  custom domain tests are run on AWS and GCP
- [x]  upgrade tests are run on k3d
- [x]  APIRule migration tests are run on k3d and AWS
- [x]  on failed workflow sent notification to slack channel mentioning commit author
- [x]  workflow names and file names adjusted to naming convention described in test strategy
- [x] changes updated in ci-cd.md

**PRs**

- [x] https://github.com/kyma-project/api-gateway/pull/1537
- [x] https://github.com/kyma-project/api-gateway/pull/1549

**ACs [PO]**

- [x]  lint and unit tests are run
- [x]  image built using image-builder
- [x]  integration tests are run on k3d and AWS
- [x]  custom domain tests are run on AWS and GCP
- [x]  upgrade tests are run on k3d
- [x]  APIRule migration tests are run on k3d and AWS
- [x]  on failed workflow sent notification to slack channel mentioning commit author
- [x]  workflow names and file names adjusted to naming convention described in test strategy
- [x] changes updated in ci-cd.md

**Attachments**

- part of: https://github.com/kyma-project/api-gateway/issues/1509
