### ISSUE TITLE
Service Namespace doesn't work in Istio JWT

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#168]
**Description**

If Istio JWT specifies Namespace for given Service, Istio resources (RA, AP) should be created in the Service namespace. If service is not specified it should use spec service from root level.

If namespace is defined on path level it should be taken, if namespaces is defined on root level it should be taken, if none of this defined then APIRule namespace should be taken.

**Expected result**

Istio resources created in configured namespace

**Actual result**

Istio resources created in APIRule namespace

**Steps to reproduce**

1. configure FT to Istio 
2. apply APIRule with service configuration in jwt handler

**Troubleshooting**
depends on: https://github.com/kyma-project/api-gateway/issues/162
be aware of k8s owner reference garbage collector
initial implementation: https://github.com/kyma-project/api-gateway/pull/153

**ToDos**:
- [x] Research current state and breakdown
- [x] Reuse old PR and adapt to new codeline
- [x] Refactor AP and RA unit tests, a lot of code duplication
- [x] Add additional unit tests
- [x] Do manual validation / tests  (check APIRule namespace change on APs test not working)

**PR**:
- [x] https://github.com/kyma-project/api-gateway/pull/184
