### ISSUE TITLE
JWT Istio based access strategy handler

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#30]
**Description**

Implement JWT handler based on Istio resources: [RequestAuthentication](https://istio.io/latest/docs/reference/config/security/request_authentication/) and [AuthorizationPolicy](https://istio.io/latest/docs/reference/config/security/authorization-policy). JWT Istio based handler should look like as proposed:

```
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: service-secured
spec:
  gateway: kyma-system/kyma-gateway
  host: foo.bar
  service:
    name: foo-service
    port: 8080
  rules:
    - path: /.*
      methods: ["GET"]
      mutators: []
      accessStrategies:
        - handler: jwtIstio
          config:
            authentications:
            - issuer: ISSUER
              jwksUri: JWKSURI
            - xxx
            authorizations:
            - audiences: ["app1", "app2"]
            - xxx
```  

ACs:
- [x] [feature toggle for early access to jwt istio based handler](https://github.com/kyma-project/api-gateway/issues/40) 
- [x] [mvp implementation of jwt - creation](https://github.com/kyma-project/api-gateway/issues/34)
- [x] [APIRule status implementation](https://github.com/kyma-project/api-gateway/issues/84)
- [x] [APIRule finaliser implementation](https://github.com/kyma-project/api-gateway/issues/162)
- [x] [mvp implementation of jwt - updates](https://github.com/kyma-project/api-gateway/issues/41)
- [x] [support for scopes](https://github.com/kyma-project/api-gateway/issues/148)
- [x] [support for mutators](https://github.com/kyma-project/api-gateway/issues/237)
- [x] [support for token from](https://github.com/kyma-project/api-gateway/issues/279)
- [x] thread modeling
- [x] [documentation for jwt handler](https://github.com/kyma-project/api-gateway/issues/314)
- [x] [breaking changes documentation](https://github.com/kyma-project/api-gateway/issues/334)
- [x] [tutorial](https://blogs.sap.com/2023/05/29/sap-btp-kyma-runtime-istio-based-jwt-handler-sneak-peek/)

**Reasons**

Introducing jwt handler based on Istio

**Attachments**
