### ISSUE TITLE
API Gateway Operator reacting on CR creation

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#474]
**Description**

Implement first version of API Gateway operator that will install api-gateway controller with production settings. Take into consideration that in the future we need cluster flavour logic implemented and based on that api-gateway should be installed in eval or prod settings respectively. Cluster flavour and eval settings are out of scope for this task. 

Implementation should be merged to feature branch that later on will be merged to main branch.

ACs:
- [x] Modularization of existing api-gateway manager
- [x] Deployment of module with LM is tested in local k3d
- [x] New APIGateway CR exists and is reconciled
- [x] documentation created
- [x] Create follow-up task to remove APIRule v1alpha1 types and async APIRule type comments with APIRule CRD in api-gateway, so the generation doesn't overwrite existing CRD: https://github.com/kyma-project/api-gateway/issues/489
- [x] Create follow-up task to deal with startup parameters `service-blocklist`, `domain-allowlist` and `generated-objects-labels`: https://github.com/kyma-project/api-gateway/issues/490
- [x] Create follow-up to discuss and implement APIGateway CR validation on reconciliation: https://github.com/kyma-project/api-gateway/issues/491
- [x] ADR for decision to use one operator with two controllers: https://github.com/kyma-project/api-gateway/issues/495

PRs:
- https://github.com/kyma-project/api-gateway/pull/487
- https://github.com/kyma-project/api-gateway/pull/493
- https://github.com/kyma-project/api-gateway/pull/496

**Reasons**

Modularisation of kyma components

**DoD:**
- [x] provide documentation
~~- [ ] release notes and What's New updates for Kyma customers~~
- [x] provide integration tests
~~- [ ] test on production-like environment~~
- [x] verify resource limits
~~- [ ] followup issue~~
~~- [ ] create release and bump in kyma~~
~~- [ ] PR reviewer will verify code coverage and evaluate if it is acceptable~~

**Attachments**
