### ISSUE TITLE
APIRule supports CORS configuration

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#705]
**Description**

Enhance APIRule API by exposing CORS configuration. Atm there is no possibility to configure CORS at all. During processing of APIRule Istio VirtualService is created with default CORS configuration. Users should be able to provide more specific configuration. It should be possible to configure allowed origins and methods. This configuration should be root configuration for APIRule. 

TODO:
- [x] [propose API](https://github.com/kyma-project/api-gateway/issues/733)
- [x] [ADR](https://github.com/kyma-project/api-gateway/issues/752)
~~- [ ] thread modeling~~
- [x] [implementation](https://github.com/kyma-project/api-gateway/issues/753)
- [x] integration tests
- [x] configuration validation
- [x] documentation

Decisions:
- [ ] what should be default settings (we can stick to what is conf atm)

**Reasons**

Allow users to provide more fined grained CORS configuration for exposed workload

**DoD:**
- [ ] Create a follow-up issue.
- [x] Provide unit tests.
- [x] Provide integration tests.
- [x] Provide documentation.
- [x] Test on a production-like environment.
- [x] Check the outcome of all related pipelines.
- [x] Verify resource limits.
- [x] As a PR reviewer, verify code coverage and evaluate if it is acceptable.
~~- [ ] Create a release and bump in Kyma.~~
- [x] Add release notes and What's New notes for Kyma customers.

**Attachments**
https://istio.io/latest/docs/reference/config/networking/virtual-service/#CorsPolicy
