### ISSUE TITLE
APIRule v2alpha1

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#939]
**Description**

Introduce APIRule 1beta2 to showcase coming changes: dropping ORY Oathkeeper and closer integration with Istio (JWT and external authorizer). Users will have a chance to get familiar with API and breaking changes. This will also give opportunity to design migration path. Finally it is a way to collect feedback and harden implementation.

Assumption is that this version will be promoted to v1 without significant changes of API and functionality if it's possible.

Tasks:
- [x] [v1beta2 API proposal](https://github.com/kyma-project/api-gateway/issues/940)
- [x] [introducing version with breaking changes POC](https://github.com/kyma-project/api-gateway/issues/970) 
- [x] [v2alpha1 renaming](https://github.com/kyma-project/api-gateway/issues/1088)
- [x] [[POC] v1beta1 -> v2alpha1 migration](https://github.com/kyma-project/api-gateway/issues/1128)
- [x] [migration mode](https://github.com/kyma-project/api-gateway/issues/1092)
- [x] [refactoring](https://github.com/kyma-project/api-gateway/issues/1016)
- [x] [implementation of no_auth and jwt](https://github.com/kyma-project/api-gateway/issues/986)
- [x] adjust CORS default settings
- [x] [implementation of ext_auth](https://github.com/kyma-project/api-gateway/issues/1245)
- [x] [mutators support](https://github.com/kyma-project/api-gateway/issues/1194)
- [x] [short host support](https://github.com/kyma-project/api-gateway/issues/1247)
- [x] include v1beta2 in documentation
- [x] blogpost
- [x] [UI ](https://github.com/kyma-project/api-gateway/issues/1353)

**Reasons**

Introduce changes to APIRule API

**DoD:**
- [x] Provide unit and integration tests.
- [x] Provide documentation.
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
~~- [ ] If you changed the resource limits, explain why it was needed.~~
~~- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.~~
- [x] Add release notes.

**Attachments**
part of #322

**Comment by strekm** [comment]
Migration blog posts published: 
- https://community.sap.com/t5/technology-blogs-by-sap/sap-btp-kyma-runtime-apirule-migration-noauth-and-jwt-handlers/ba-p/13882833
- https://community.sap.com/t5/technology-blogs-by-sap/sap-btp-kyma-runtime-apirule-migration-ory-oathkeeper-based-oauth2-handlers/ba-p/13896184

**Comment by strekm** [comment]
API Gateway 2.8.0 introducing UI supporting APIRule v2alpha1 in Kyma dashboard was rolled out to fast channel on 29.10 and it is scheduled to be promoted to regular channel on 12.11 for managed Kyma offering
