### ISSUE TITLE
Fix Istio JWT handler issue with Ory type of handlers

### ISSUE THREAD

**Issue by barchw** [kyma-project/api-gateway#96]
**Description**
When using `Ory` secured type of handler when the JWT handler is set to Istio no `Rule` resource is created

**Further notice**
This issue will most likely also happen when the APIRule is exposed with multiple handlers for one path because of this logic, which only checks whether there is at least one handler with `JWT` type: https://github.com/kyma-project/api-gateway/blob/fc3002f3f6c4ae2e7ff4d77d65e142f43573fcec/internal/processing/helpers.go#L25

**Steps to reproduce**
1. Deploy API Gateway controller in latest feature branch version
2. Set ConfigMap configuration to Istio handler
3. Create APIRule with `noop` or `oauth2_introspection` type of handler

**What happens**
No Rule is created and Ory proxy fails to route to the exposed service

**Troubleshooting**
The bug most likely comes from this logic running on every type of `secured` rule: https://github.com/kyma-project/api-gateway/blob/fc3002f3f6c4ae2e7ff4d77d65e142f43573fcec/internal/processing/processing.go#L73

**ToDos**:
- [x] Refactor processing to support mixed case with Istio JWT and Ory handlers
- [x] Unit tests to validate new use-case
- [x] Add validation for unsupported scenarios and tests
- [x] Refactor AP and RA processors for handling mixed JWT+Ory case
- [x] Tests for AP, RA on managing objects
- [x] Manual validation if reported bugs are fixed
- [x] Review and merge in feature branch

**PR**:
- https://github.com/kyma-project/api-gateway/pull/119

**Comment by videlov** [comment]
*PR*:
- https://github.com/kyma-project/api-gateway/pull/119
