### ISSUE TITLE
[POC] Introduction of version containing breaking changes

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#970]
**Description**

Goal of this task is explore technical solutions to introduce CRD version that will contain breaking changes. v1beta2 version will introduce 3 handlers: noAuth, jwt and extAuth. noAuth handler is part of v1beta1, jwt handler is part of v1beta1 but logic is different, extAuth is not part of v1beta1.

Stored API version should be v1beta1. This means that beta2 needs to be converted to beta1 version. there should be any problem with converting noAuth. In case of jwt handler challenge would be to keep Istio based logic implementation. In case of of extAuth challenge would be to with storage version beta1, where this handler is not existing.

In first iteration only handlers noAuth and jwt will be introduced. extAuth will follow. 

Consider introducing conversion webhook if needed.

**TODOs**
- [x] get familiar with versioning concepts in k8s, [more info](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#overview)
- [x] evaluate what are the incompatible changes coming with v1beta2
- [x] check out conversion webhook approach, [more info](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion)
  skip this for now because we [already did that](https://github.com/kyma-project/api-gateway/commit/999c02ca555e735a9b6f5c245803b7cf181443be) for v1alpha1->v1beta1 (e.g. moved required `host` field from `service` to root `spec` level), [example GVK conversion](https://github.com/kubernetes/kubernetes/blob/434bfd82814af038ad94d62ebe59b133fcb50506/test/images/agnhost/crd-conversion-webhook/converter/framework.go#L117)
- [x] evaluation options - since only single version is allowed to be stored in the `etcd` at any single time, only option is to use conversion webhook. procedure described [in here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#overview)
- [x] document findings about manual / automated [migration of storage version in knowledge-hub](https://github.tools.sap/xf-goat/knowledge-hub/tree/master/crd-storage-migration)
- [x] consider drawbacks from when we were running the conversion webhook - after talking to Bartek, this should be fine for now and we can reconsider when implementing it.
- [x] check how to handle v1beta2 with stored v1beta1 (should we introduce a in between version, including unknown fields for v1beta2 stuff)
- [x] document conversion spec for v1beta1 <-> v1beta2

**Migration options after deprecations**:
- Manual migration (if applicable / open source), [more info](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version)
- Storage Version Migrator is an option, [more info](https://github.com/kubernetes-sigs/kube-storage-version-migrator/blob/master/USER_GUIDE.md)

**Findings**
- Breaking changes in CRD versions can be solved **only** with conversion webhook (we already had it before)
- Migration options [documented in knowledge-hub page](https://github.tools.sap/xf-goat/knowledge-hub/tree/master/crd-storage-migration)
- Applying v1beta1 and v1beta2 APIRules with [conversion webhook and annotations](https://github.tools.sap/xf-goat/knowledge-hub/tree/master/apirule-v1beta1-v1beta2)

**Reasons**

**DoD:**
~~- [ ] Provide unit and integration tests.~~
- [x] Provide documentation.
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
~~- [ ] If you changed the resource limits, explain why it was needed.~~
~~- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.~~
~~- [ ] Add release notes.~~

**Attachments**
part of: #939

**PRs and POC projects**
- https://github.com/videlov/cert-gen (certificate generation need for the webhook)
- https://github.com/videlov/crd-conversion-webhook (conversion webhook)
- https://github.com/kyma-project/api-gateway/pull/982 (API Gateway POC)

**Additional**
Good blogpost: https://faun.dev/c/stories/dineshparvathaneni/kubernetes-crd-versioning-for-operator-developers/
